
export enum CategoryType {
  Food = 'Comida',
  Transport = 'Transporte',
  Housing = 'Vivienda',
  Entertainment = 'Entretenimiento',
  Health = 'Salud',
  Shopping = 'Compras',
  Savings = 'Ahorro',
  Others = 'Otros'
}

export enum IncomeCategoryType {
  Salary = 'Salario',
  Business = 'Negocio',
  Gift = 'Regalo',
  Sale = 'Venta',
  Investment = 'Inversión',
  Loan = 'Préstamo',
  Other = 'Otros'
}

// Allow dynamic categories (strings)
export type Category = CategoryType | string;

export interface Expense {
  id: string;
  amount: number;
  category: Category;
  description: string;
  date: string; // ISO string
  isFixed?: boolean;
  accountId?: string;
}

export interface Income {
  id: string;
  amount: number;
  category: string;
  description: string;
  date: string;
  accountId: string;
}

export interface Budget {
  category: Category;
  limit: number;
  spent: number;
  color: string;
}

export type PeriodType = 'Mensual' | 'Quincenal' | 'Semanal' | 'Bimestral' | 'Semestral' | 'Anual';

export interface User {
  id: string;
  email: string;
  name: string;
  currency: string;
  monthlyLimit: number; // This acts as the "Period Limit" now
  periodType: PeriodType;
  periodStartDay: number; // 1-31
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: number;
}

export interface RecurringItem {
  id: string;
  name: string;
  amount: number; // Estimated amount for variable items
  category: Category;
  frequency: 'Mensual' | 'Anual' | 'Semanal' | 'Quincenal' | 'Trimestral';
  nextDate: string;
  isVariable?: boolean; // NEW: If true, asks user for amount before creating expense
}

export interface AuthSession {
  user: User | null;
  token: string | null;
}

// --- NEW TYPES FOR GOALS & WALLET ---

// Added 'Loan' for personal debts
export type AccountType = 'Debit' | 'Credit' | 'Cash' | 'Investment' | 'Loan';

export interface Account {
  id: string;
  name: string;
  type: AccountType;
  balance: number; // For Credit/Loan, this is debt (positive number usually treated as negative in net worth)
  limit?: number; // Only for Credit Cards
  color: string;
  lastDigits?: string;
  isDefault?: boolean;
}

export interface FinancialGoal {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  deadline: string; // ISO Date
  aiPlan?: string; // The detailed plan generated by AI
  monthlyContribution?: number; // NEW: How much to save per period to hit goal
  icon?: string;
  color?: string; // NEW: User defined color
}