
import React, { useState, useEffect } from 'react';
import { Icons } from '../components/Icons';
import { RecurringItem, CategoryType } from '../types';
import { dbService } from '../services/dbService';
import { BarChart, Bar, XAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';

export const RecurringExpenses: React.FC = () => {
  const [items, setItems] = useState<RecurringItem[]>([]);
  const [categoriesList, setCategoriesList] = useState<{name: string}[]>([]);
  const [loading, setLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedItem, setSelectedItem] = useState<RecurringItem | null>(null);
  
  // Form
  const [name, setName] = useState('');
  const [amount, setAmount] = useState('');
  const [frequency, setFrequency] = useState('Mensual');
  const [category, setCategory] = useState<string>('');
  const [nextPaymentDate, setNextPaymentDate] = useState(new Date().toISOString().split('T')[0]); // Default today
  const [isCustomCategory, setIsCustomCategory] = useState(false);
  const [isVariable, setIsVariable] = useState(false);

  // Load from DB
  useEffect(() => {
      refreshData();
  }, []);

  const refreshData = async () => {
      setLoading(true);
      try {
        const [itemsData, catsData] = await Promise.all([
            dbService.getRecurringExpenses(),
            dbService.getCategories()
        ]);
        setItems(itemsData);
        
        // Set categories
        if (catsData && catsData.length > 0) {
            setCategoriesList(catsData);
        } else {
            // Fallback defaults if DB is empty
            setCategoriesList(Object.values(CategoryType).map(c => ({ name: c })));
        }
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
  };

  // Helper to ensure consistent formatting: 22 feb 2025 (ignores Timezone)
  const formatDateFriendly = (isoDate: string) => {
    if (!isoDate) return '';
    // Parse manually to avoid timezone shifts (split YYYY-MM-DD)
    const parts = isoDate.split('-');
    if (parts.length < 3) return isoDate;
    
    const year = parseInt(parts[0]);
    const month = parseInt(parts[1]) - 1; // 0-indexed
    const day = parseInt(parts[2]);
    
    const date = new Date(year, month, day);

    return new Intl.DateTimeFormat('es-MX', {
        day: 'numeric',
        month: 'short',
        year: 'numeric'
    }).format(date);
  };

  const handleDelete = async (id: string) => {
    if (window.confirm('¿Eliminar este gasto fijo?')) {
        await dbService.deleteRecurringExpense(id);
        refreshData();
        setSelectedItem(null);
    }
  };

  const handleAdd = async (e: React.FormEvent) => {
    e.preventDefault();
    
    try {
        let finalCategory = category;
        
        // Save new category if custom
        if (isCustomCategory && category) {
            const exists = categoriesList.some(c => c.name.toLowerCase() === category.toLowerCase());
            if (!exists) {
                await dbService.createCategory(category);
            }
            finalCategory = category;
        } else if (!category && categoriesList.length > 0) {
            finalCategory = categoriesList[0].name;
        }

        const newItem: RecurringItem = {
            id: '', // Generated by DB
            name,
            amount: parseFloat(amount),
            category: finalCategory,
            frequency: frequency as any,
            nextDate: nextPaymentDate, // Use user selected date string directly
            isVariable
        };

        await dbService.addRecurringExpense(newItem);
        await refreshData();
        setIsModalOpen(false);
        resetForm();
    } catch (e) {
        alert("Error al guardar. Asegúrate de la conexión a Supabase.");
    }
  };

  const resetForm = () => {
      setName('');
      setAmount('');
      setCategory('');
      setNextPaymentDate(new Date().toISOString().split('T')[0]);
      setIsCustomCategory(false);
      setIsVariable(false);
  };

  const handleOpenModal = () => {
      resetForm();
      // Pre-select first category if available
      if (categoriesList.length > 0) {
          setCategory(categoriesList[0].name);
      } else {
          setCategory(CategoryType.Others);
      }
      setIsModalOpen(true);
  };

  const totalFixed = items.reduce((sum, item) => sum + item.amount, 0);

  if (loading && items.length === 0) return <div className="p-10 text-center text-gray-400">Cargando gastos fijos...</div>;

  return (
    <div className="space-y-6 pb-24">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold">Gastos Fijos</h1>
        <button 
            onClick={handleOpenModal}
            className="bg-primary text-white px-4 py-2 rounded-xl shadow-md hover:bg-purple-600 flex items-center gap-2 transition-colors"
        >
            <Icons.Add size={20} />
            <span className="hidden sm:inline">Agregar</span>
        </button>
      </div>

      {/* Summary Card */}
      <div className="bg-indigo-600 text-white p-6 rounded-3xl shadow-lg flex justify-between items-center">
        <div>
            <p className="text-indigo-200 text-sm">Total recurrente (Estimado)</p>
            <h2 className="text-3xl font-bold mt-1">${totalFixed.toLocaleString()}</h2>
        </div>
        <div className="bg-white/20 p-3 rounded-full">
            <Icons.Calendar size={32} />
        </div>
      </div>

      <div className="grid gap-4">
        {items.map(item => (
            <div 
                key={item.id} 
                onClick={() => setSelectedItem(item)}
                className={`bg-white p-4 rounded-2xl shadow-sm flex flex-col sm:flex-row sm:items-center justify-between group hover:shadow-md transition-all gap-4 cursor-pointer border ${item.isVariable ? 'border-l-4 border-l-orange-400' : 'border-transparent'} hover:border-primary/20`}
            >
                <div className="flex items-center gap-4">
                    <div className={`w-12 h-12 rounded-xl flex items-center justify-center font-bold text-lg shrink-0 ${item.isVariable ? 'bg-orange-50 text-orange-500' : 'bg-gray-50 text-gray-500'}`}>
                        {item.name.charAt(0)}
                    </div>
                    <div>
                        <h3 className="font-bold text-textPrimary flex items-center gap-2">
                            {item.name}
                            {item.isVariable && <Icons.Settings size={14} className="text-orange-400" />}
                        </h3>
                        <div className="flex items-center gap-2 text-xs text-textSecondary">
                             <span className="bg-gray-100 px-2 py-0.5 rounded text-gray-600">{item.category}</span>
                             <span>• {item.frequency}</span>
                             <span className={item.nextDate < new Date().toISOString().split('T')[0] ? 'text-red-500 font-bold' : ''}>
                                • Próx: {formatDateFriendly(item.nextDate)}
                             </span>
                        </div>
                    </div>
                </div>
                <div className="flex items-center justify-between sm:justify-end gap-4 w-full sm:w-auto border-t sm:border-t-0 border-gray-50 pt-3 sm:pt-0">
                    <div className="text-right">
                        <span className="font-bold text-textPrimary text-lg">
                            {item.isVariable ? '~' : ''}${item.amount}
                        </span>
                        {item.isVariable && <p className="text-[10px] text-orange-400 font-medium">Monto Variable</p>}
                    </div>
                    <Icons.ArrowUpRight size={16} className="text-gray-300" />
                </div>
            </div>
        ))}
        {items.length === 0 && (
            <div className="text-center py-10 text-gray-400">
                No tienes gastos fijos configurados.
            </div>
        )}
      </div>

      {/* Create Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/50 z-[60] flex items-center justify-center p-4 backdrop-blur-sm">
            <div className="bg-white rounded-3xl p-6 w-full max-w-sm shadow-2xl animate-fade-in max-h-[90vh] overflow-y-auto">
                <div className="flex justify-between items-center mb-6">
                    <h2 className="text-xl font-bold">Nuevo Gasto Fijo</h2>
                    <button onClick={() => setIsModalOpen(false)} className="text-gray-400 hover:text-gray-600">
                        <Icons.Close size={24} />
                    </button>
                </div>

                <form onSubmit={handleAdd} className="space-y-4">
                    <div>
                        <label className="block text-xs font-bold text-textSecondary uppercase mb-2">Nombre</label>
                        <input 
                            type="text" 
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            className="w-full bg-background p-3 rounded-xl outline-none focus:ring-2 focus:ring-primary"
                            placeholder="Ej. CFE / Luz"
                            required
                        />
                    </div>

                    <div>
                        <label className="block text-xs font-bold text-textSecondary uppercase mb-2">Categoría</label>
                        {!isCustomCategory ? (
                            <div className="flex gap-2 items-center bg-background p-3 rounded-xl focus-within:ring-2 focus-within:ring-primary">
                                <select 
                                    value={category}
                                    onChange={(e) => {
                                        if (e.target.value === 'new_custom') {
                                            setIsCustomCategory(true);
                                            setCategory('');
                                        } else {
                                            setCategory(e.target.value);
                                        }
                                    }}
                                    className="w-full bg-transparent outline-none text-textPrimary"
                                >
                                    {categoriesList.map(c => (
                                        <option key={c.name} value={c.name}>{c.name}</option>
                                    ))}
                                    <option value="new_custom" className="text-primary font-bold">+ Nueva Categoría</option>
                                </select>
                            </div>
                        ) : (
                            <div className="flex gap-2">
                                <input 
                                    type="text"
                                    value={category}
                                    onChange={(e) => setCategory(e.target.value)}
                                    placeholder="Nombre de nueva categoría"
                                    className="flex-1 bg-background p-3 rounded-xl outline-none focus:ring-2 focus:ring-primary"
                                    autoFocus
                                />
                                <button 
                                    type="button"
                                    onClick={() => { 
                                        setIsCustomCategory(false); 
                                        setCategory(categoriesList.length > 0 ? categoriesList[0].name : ''); 
                                    }}
                                    className="px-3 bg-gray-200 rounded-xl text-gray-600 hover:bg-gray-300 transition-colors"
                                >
                                    <Icons.Close size={16} />
                                </button>
                            </div>
                        )}
                    </div>

                    {/* Is Variable Toggle */}
                    <div 
                        onClick={() => setIsVariable(!isVariable)}
                        className={`p-3 rounded-xl border flex items-start gap-3 cursor-pointer transition-colors ${isVariable ? 'bg-orange-50 border-orange-200' : 'bg-gray-50 border-transparent'}`}
                    >
                        <div className={`w-5 h-5 rounded border mt-0.5 flex items-center justify-center shrink-0 ${isVariable ? 'bg-orange-500 border-orange-500 text-white' : 'border-gray-400 bg-white'}`}>
                            {isVariable && <Icons.Check size={14} />}
                        </div>
                        <div>
                            <span className={`text-sm font-bold ${isVariable ? 'text-orange-700' : 'text-gray-600'}`}>Monto Variable</span>
                            <p className="text-xs text-gray-500 leading-tight mt-1">
                                Actívalo si el precio cambia cada mes (Luz, Gas). La app te pedirá confirmar el monto exacto el día del pago.
                            </p>
                        </div>
                    </div>

                    <div>
                        <label className="block text-xs font-bold text-textSecondary uppercase mb-2">
                            {isVariable ? 'Monto Estimado (Promedio)' : 'Monto Fijo'}
                        </label>
                        <div className="relative">
                            <span className="absolute left-4 top-1/2 -translate-y-1/2 text-textPrimary font-bold">$</span>
                            <input 
                                type="number" 
                                value={amount}
                                onChange={(e) => setAmount(e.target.value)}
                                className="w-full bg-background p-3 pl-8 rounded-xl outline-none focus:ring-2 focus:ring-primary font-bold text-lg"
                                required
                            />
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                        <div>
                            <label className="block text-xs font-bold text-textSecondary uppercase mb-2">Frecuencia</label>
                            <select 
                                value={frequency}
                                onChange={(e) => setFrequency(e.target.value)}
                                className="w-full bg-background p-3 rounded-xl outline-none focus:ring-2 focus:ring-primary"
                            >
                                <option value="Mensual">Mensual</option>
                                <option value="Semanal">Semanal</option>
                                <option value="Anual">Anual</option>
                                <option value="Bimestral">Bimestral</option>
                            </select>
                        </div>
                        <div>
                             <label className="block text-xs font-bold text-textSecondary uppercase mb-2">Próximo Pago</label>
                             <input 
                                type="date"
                                value={nextPaymentDate}
                                onChange={(e) => setNextPaymentDate(e.target.value)}
                                className="w-full bg-background p-3 rounded-xl outline-none focus:ring-2 focus:ring-primary text-sm"
                                required
                             />
                        </div>
                    </div>
                    
                    <div className="bg-gray-50 p-3 rounded-xl flex gap-2 items-start border border-gray-100">
                        <Icons.Calendar className="text-primary mt-0.5 shrink-0" size={14} />
                        <p className="text-[10px] text-gray-500 leading-tight">
                            Tu próximo pago será el <strong>{formatDateFriendly(nextPaymentDate)}</strong>. 
                            El sistema calculará automáticamente las siguientes fechas basándose en este día.
                        </p>
                    </div>

                    <div className="pt-2">
                        <button 
                            type="submit"
                            className="w-full py-3 rounded-xl font-semibold bg-primary text-white hover:bg-purple-600 shadow-lg shadow-primary/30"
                        >
                            Guardar Gasto Fijo
                        </button>
                    </div>
                </form>
            </div>
        </div>
      )}

      {/* Detail Modal with Chart */}
      {selectedItem && (
          <div className="fixed inset-0 bg-black/50 z-[60] flex items-center justify-center p-4 backdrop-blur-sm">
             <div className="bg-white rounded-3xl p-6 w-full max-w-sm shadow-2xl animate-fade-in">
                <div className="flex justify-between items-start mb-4">
                    <div className="flex items-center gap-3">
                        <div className="w-12 h-12 bg-indigo-100 rounded-xl flex items-center justify-center text-indigo-600 font-bold text-xl">
                            {selectedItem.name.charAt(0)}
                        </div>
                        <div>
                            <h2 className="text-xl font-bold">{selectedItem.name}</h2>
                            <p className="text-sm text-gray-500">{selectedItem.category}</p>
                        </div>
                    </div>
                    <button onClick={() => setSelectedItem(null)} className="text-gray-400 hover:text-gray-600">
                        <Icons.Close size={24} />
                    </button>
                </div>

                <div className="bg-gray-50 rounded-2xl p-4 mb-6 text-center">
                    <p className="text-xs text-gray-400 uppercase font-bold tracking-wide">
                        {selectedItem.isVariable ? 'Promedio' : 'Costo'} {selectedItem.frequency}
                    </p>
                    <p className="text-3xl font-bold text-textPrimary mt-1">
                        {selectedItem.isVariable && '~'}$ {selectedItem.amount}
                    </p>
                    <div className="flex flex-col items-center gap-1 mt-2">
                        {selectedItem.isVariable && (
                            <span className="inline-block bg-orange-100 text-orange-600 text-[10px] font-bold px-2 py-1 rounded-lg">
                                Variable: Se confirma manualmente
                            </span>
                        )}
                        <span className="inline-block bg-blue-50 text-blue-600 text-[10px] font-bold px-2 py-1 rounded-lg">
                            Próximo: {formatDateFriendly(selectedItem.nextDate)}
                        </span>
                    </div>
                </div>

                <div className="flex gap-2">
                     <button 
                        onClick={() => handleDelete(selectedItem.id)}
                        className="flex-1 py-3 rounded-xl border border-red-100 text-red-500 font-semibold hover:bg-red-50 transition-colors"
                     >
                        Eliminar
                     </button>
                     <button 
                        onClick={() => setSelectedItem(null)}
                        className="flex-1 py-3 rounded-xl bg-primary text-white font-semibold hover:bg-purple-600 shadow-lg shadow-primary/20"
                     >
                        Cerrar
                     </button>
                </div>
             </div>
          </div>
      )}
    </div>
  );
};
